/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef FOXRTC_WRAP_H
#define FOXRTC_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void* _wrap_new_FoxrtcTransport();
void _wrap_delete_FoxrtcTransport(void* imarg1);
int _wrap_FoxrtcTransport_SendRtp(void* imarg1, NSString * imarg2, int imarg3);
int _wrap_FoxrtcTransport_SendRtcp(void* imarg1, NSString * imarg2, int imarg3);
void _wrap_delete_Foxrtc(void* imarg1);
void* _wrap_Foxrtc_Instance();
int _wrap_Foxrtc_Init(void* imarg1, void* imarg2);
int _wrap_Foxrtc_Uninit(void* imarg1);
int _wrap_Foxrtc_GetDeviceInfo(void* imarg1);
int _wrap_Foxrtc_OpenCamera(void* imarg1, int imarg2);
int _wrap_Foxrtc_CloseCamera(void* imarg1);
int _wrap_Foxrtc_CreateLocalAudioStream(void* imarg1, unsigned int imarg2);
int _wrap_Foxrtc_DeleteLocalAudioStream(void* imarg1);
int _wrap_Foxrtc_CreateRemoteAudioStream(void* imarg1, unsigned int imarg2);
int _wrap_Foxrtc_DeleteRemoteAudioStream(void* imarg1);
int _wrap_Foxrtc_CreateLocalVideoStream(void* imarg1, int imarg2, void* imarg3);
int _wrap_Foxrtc_DeleteLocalVideoStream(void* imarg1);
int _wrap_Foxrtc_CreateRemoteVideoStream(void* imarg1, int imarg2, void* imarg3);
int _wrap_Foxrtc_DeleteRemoteVideoStream(void* imarg1);
int _wrap_Foxrtc_IncomingData(void* imarg1, NSString * imarg2, int imarg3);

#ifdef __cplusplus
}
#endif

#endif

