/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.foxrtc.android;

public class FoxrtcTransport {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FoxrtcTransport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FoxrtcTransport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Foxrtc_androidJNI.delete_FoxrtcTransport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FoxrtcTransport() {
    this(Foxrtc_androidJNI.new_FoxrtcTransport(), true);
  }

  public int SendRtp(String data, int len) {
    return Foxrtc_androidJNI.FoxrtcTransport_SendRtp(swigCPtr, this, data, len);
  }

  public int SendRtcp(String data, int len) {
    return Foxrtc_androidJNI.FoxrtcTransport_SendRtcp(swigCPtr, this, data, len);
  }

}
