/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.foxrtc.android;

public class Foxrtc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Foxrtc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Foxrtc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Foxrtc_androidJNI.delete_Foxrtc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Foxrtc Instance() {
    return new Foxrtc(Foxrtc_androidJNI.Foxrtc_Instance(), false);
  }

  public int Init(FoxrtcTransport transport) {
    return Foxrtc_androidJNI.Foxrtc_Init(swigCPtr, this, FoxrtcTransport.getCPtr(transport), transport);
  }

  public int Uninit() {
    return Foxrtc_androidJNI.Foxrtc_Uninit(swigCPtr, this);
  }

  public int GetDeviceInfo() {
    return Foxrtc_androidJNI.Foxrtc_GetDeviceInfo(swigCPtr, this);
  }

  public int OpenCamera(int index) {
    return Foxrtc_androidJNI.Foxrtc_OpenCamera(swigCPtr, this, index);
  }

  public int CloseCamera() {
    return Foxrtc_androidJNI.Foxrtc_CloseCamera(swigCPtr, this);
  }

  public int CreateLocalAudioStream(long ssrc) {
    return Foxrtc_androidJNI.Foxrtc_CreateLocalAudioStream(swigCPtr, this, ssrc);
  }

  public int DeleteLocalAudioStream() {
    return Foxrtc_androidJNI.Foxrtc_DeleteLocalAudioStream(swigCPtr, this);
  }

  public int CreateRemoteAudioStream(long ssrc) {
    return Foxrtc_androidJNI.Foxrtc_CreateRemoteAudioStream(swigCPtr, this, ssrc);
  }

  public int DeleteRemoteAudioStream() {
    return Foxrtc_androidJNI.Foxrtc_DeleteRemoteAudioStream(swigCPtr, this);
  }

  public int CreateLocalVideoStream(int ssrc, android.view.SurfaceView view) {
    return Foxrtc_androidJNI.Foxrtc_CreateLocalVideoStream(swigCPtr, this, ssrc, view);
  }

  public int DeleteLocalVideoStream() {
    return Foxrtc_androidJNI.Foxrtc_DeleteLocalVideoStream(swigCPtr, this);
  }

  public int CreateRemoteVideoStream(int ssrc, android.view.SurfaceView view) {
    return Foxrtc_androidJNI.Foxrtc_CreateRemoteVideoStream(swigCPtr, this, ssrc, view);
  }

  public int DeleteRemoteVideoStream() {
    return Foxrtc_androidJNI.Foxrtc_DeleteRemoteVideoStream(swigCPtr, this);
  }

  public int IncomingData(String data, int len) {
    return Foxrtc_androidJNI.Foxrtc_IncomingData(swigCPtr, this, data, len);
  }

}
