/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef EXAMPLE_WRAP_H
#define EXAMPLE_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void _wrap_add(int * imarg1, int * imarg2, int * imarg3);
int * _wrap_new_intp();
int * _wrap_copy_intp(int imarg1);
void _wrap_delete_intp(int * imarg1);
void _wrap_intp_assign(int * imarg1, int imarg2);
int _wrap_intp_value(int * imarg1);
void _wrap_sub(int imarg1, int imarg2, int* imarg3);
int _wrap_divide(int imarg1, int imarg2, int* imarg3);

#ifdef __cplusplus
}
#endif

#endif

