/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "example_proxy.h"
#include "example_wrap.h"

void ObjcAdd(int * x, int * y, int * result)
{
 _wrap_add(x, y, result);
}

int * ObjcNew_intp()
{
  return _wrap_new_intp(); 
}

int * ObjcCopy_intp(int value)
{
  return _wrap_copy_intp(value); 
}

void ObjcDelete_intp(int * obj)
{
 _wrap_delete_intp(obj);
}

void ObjcIntp_assign(int * obj, int value)
{
 _wrap_intp_assign(obj, value);
}

int ObjcIntp_value(int * obj)
{
  return _wrap_intp_value(obj); 
}

void ObjcSub(int arg0, int arg1, int* OUTPUT)
{
 _wrap_sub(arg0, arg1, OUTPUT);
}

int ObjcDivide(int n, int d, int* r)
{
  return _wrap_divide(n, d, r); 
}

