/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

void ObjcAdd(int * x, int * y, int * result);
int * ObjcNew_intp();
int * ObjcCopy_intp(int value);
void ObjcDelete_intp(int * obj);
void ObjcIntp_assign(int * obj, int value);
int ObjcIntp_value(int * obj);
void ObjcSub(int arg0, int arg1, int* OUTPUT);
int ObjcDivide(int n, int d, int* r);

#ifdef __cplusplus
}
#endif

